//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public int DeliveryID { get; set; }
        public int OrderID { get; set; }
        public int CourierID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Status { get; set; }
        public string TrackingNumber { get; set; }
        public string DeliveryAddress { get; set; }
        public string Notes { get; set; }
    
        public virtual Couriers Couriers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
