//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPromotions
    {
        public int ProductPromotionID { get; set; }
        public int ProductID { get; set; }
        public int PromotionID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Promotions Promotions { get; set; }
    }
}
